language: python  # this works for Linux but is an error on macOS or Windows

# python:
#   - 3.7
#   - 3.8

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      before_install:
        - sudo apt-get -y install libngspice0
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
      addons:
        homebrew:
          packages:
            - libngspice
    - name: "Python 3.8.0 on Windows"
      os: windows  # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  # all three OSes agree about 'pip3'
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  # - pip3 install .
  - python3 setup.py -q install

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - pytest unit-test
